/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_couchbase_lite_storage_JavaSQLiteStorageEngine */

#ifndef _Included_com_couchbase_lite_storage_JavaSQLiteStorageEngine
#define _Included_com_couchbase_lite_storage_JavaSQLiteStorageEngine
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_couchbase_lite_storage_JavaSQLiteStorageEngine
 * Method:    _open
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_couchbase_lite_storage_JavaSQLiteStorageEngine__1open
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_couchbase_lite_storage_JavaSQLiteStorageEngine
 * Method:    _getVersion
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_couchbase_lite_storage_JavaSQLiteStorageEngine__1getVersion
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_couchbase_lite_storage_JavaSQLiteStorageEngine
 * Method:    _setVersion
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_couchbase_lite_storage_JavaSQLiteStorageEngine__1setVersion
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_couchbase_lite_storage_JavaSQLiteStorageEngine
 * Method:    _beginTransaction
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_couchbase_lite_storage_JavaSQLiteStorageEngine__1beginTransaction
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_couchbase_lite_storage_JavaSQLiteStorageEngine
 * Method:    _commit
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_couchbase_lite_storage_JavaSQLiteStorageEngine__1commit
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_couchbase_lite_storage_JavaSQLiteStorageEngine
 * Method:    _rollback
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_couchbase_lite_storage_JavaSQLiteStorageEngine__1rollback
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_couchbase_lite_storage_JavaSQLiteStorageEngine
 * Method:    _execute
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_couchbase_lite_storage_JavaSQLiteStorageEngine__1execute__JLjava_lang_String_2
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_couchbase_lite_storage_JavaSQLiteStorageEngine
 * Method:    _execute
 * Signature: (JLjava/lang/String;[Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_com_couchbase_lite_storage_JavaSQLiteStorageEngine__1execute__JLjava_lang_String_2_3Ljava_lang_Object_2
  (JNIEnv *, jobject, jlong, jstring, jobjectArray);

/*
 * Class:     com_couchbase_lite_storage_JavaSQLiteStorageEngine
 * Method:    _query
 * Signature: (JLjava/lang/String;[Ljava/lang/String;)Lcom/couchbase/lite/storage/JavaSQLiteStorageEngine/StatementCursor;
 */
JNIEXPORT jobject JNICALL Java_com_couchbase_lite_storage_JavaSQLiteStorageEngine__1query
  (JNIEnv *, jobject, jlong, jstring, jobjectArray);

/*
 * Class:     com_couchbase_lite_storage_JavaSQLiteStorageEngine
 * Method:    _insert
 * Signature: (JLjava/lang/String;[Ljava/lang/Object;)J
 */
JNIEXPORT jlong JNICALL Java_com_couchbase_lite_storage_JavaSQLiteStorageEngine__1insert
  (JNIEnv *, jobject, jlong, jstring, jobjectArray);

/*
 * Class:     com_couchbase_lite_storage_JavaSQLiteStorageEngine
 * Method:    _update
 * Signature: (JLjava/lang/String;[Ljava/lang/Object;)I
 */
JNIEXPORT jint JNICALL Java_com_couchbase_lite_storage_JavaSQLiteStorageEngine__1update
  (JNIEnv *, jobject, jlong, jstring, jobjectArray);

/*
 * Class:     com_couchbase_lite_storage_JavaSQLiteStorageEngine
 * Method:    _delete
 * Signature: (JLjava/lang/String;[Ljava/lang/Object;)I
 */
JNIEXPORT jint JNICALL Java_com_couchbase_lite_storage_JavaSQLiteStorageEngine__1delete
  (JNIEnv *, jobject, jlong, jstring, jobjectArray);

/*
 * Class:     com_couchbase_lite_storage_JavaSQLiteStorageEngine
 * Method:    _close
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_couchbase_lite_storage_JavaSQLiteStorageEngine__1close
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_couchbase_lite_storage_JavaSQLiteStorageEngine
 * Method:    nativeTestCollateJson
 * Signature: (ILjava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_couchbase_lite_storage_JavaSQLiteStorageEngine_nativeTestCollateJson
  (JNIEnv *, jclass, jint, jstring, jstring);

/*
 * Class:     com_couchbase_lite_storage_JavaSQLiteStorageEngine
 * Method:    nativeTestCollateRevIds
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_couchbase_lite_storage_JavaSQLiteStorageEngine_nativeTestCollateRevIds
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
