/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_couchbase_lite_storage_JavaSQLiteStorageEngine */

#ifndef _Included_com_couchbase_lite_storage_JavaSQLiteStorageEngine
#define _Included_com_couchbase_lite_storage_JavaSQLiteStorageEngine
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_couchbase_lite_storage_JavaSQLiteStorageEngine
 * Method:    open
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_couchbase_lite_storage_JavaSQLiteStorageEngine__1open
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_couchbase_lite_storage_JavaSQLiteStorageEngine
 * Method:    getVersion
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_couchbase_lite_storage_JavaSQLiteStorageEngine_getVersion
  (JNIEnv *, jobject);

/*
 * Class:     com_couchbase_lite_storage_JavaSQLiteStorageEngine
 * Method:    setVersion
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_couchbase_lite_storage_JavaSQLiteStorageEngine_setVersion
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_couchbase_lite_storage_JavaSQLiteStorageEngine
 * Method:    beginTransaction
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_couchbase_lite_storage_JavaSQLiteStorageEngine_beginTransaction
  (JNIEnv *, jobject);

/*
 * Class:     com_couchbase_lite_storage_JavaSQLiteStorageEngine
 * Method:    _commit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_couchbase_lite_storage_JavaSQLiteStorageEngine__1commit
  (JNIEnv *, jobject);

/*
 * Class:     com_couchbase_lite_storage_JavaSQLiteStorageEngine
 * Method:    _rollback
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_couchbase_lite_storage_JavaSQLiteStorageEngine__1rollback
  (JNIEnv *, jobject);

/*
 * Class:     com_couchbase_lite_storage_JavaSQLiteStorageEngine
 * Method:    _execute
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_couchbase_lite_storage_JavaSQLiteStorageEngine__1execute__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_couchbase_lite_storage_JavaSQLiteStorageEngine
 * Method:    _execute
 * Signature: (Ljava/lang/String;[Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_com_couchbase_lite_storage_JavaSQLiteStorageEngine__1execute__Ljava_lang_String_2_3Ljava_lang_Object_2
  (JNIEnv *, jobject, jstring, jobjectArray);

/*
 * Class:     com_couchbase_lite_storage_JavaSQLiteStorageEngine
 * Method:    _query
 * Signature: (Ljava/lang/String;[Ljava/lang/String;)Lcom/couchbase/cblite/storage/JavaSQLiteStorageEngine/StatementCursor;
 */
JNIEXPORT jobject JNICALL Java_com_couchbase_lite_storage_JavaSQLiteStorageEngine__1query
  (JNIEnv *, jobject, jstring, jobjectArray);

/*
 * Class:     com_couchbase_lite_storage_JavaSQLiteStorageEngine
 * Method:    _insert
 * Signature: (Ljava/lang/String;[Ljava/lang/Object;)J
 */
JNIEXPORT jlong JNICALL Java_com_couchbase_lite_storage_JavaSQLiteStorageEngine__1insert
  (JNIEnv *, jobject, jstring, jobjectArray);

/*
 * Class:     com_couchbase_lite_storage_JavaSQLiteStorageEngine
 * Method:    _update
 * Signature: (Ljava/lang/String;[Ljava/lang/Object;)I
 */
JNIEXPORT jint JNICALL Java_com_couchbase_lite_storage_JavaSQLiteStorageEngine__1update
  (JNIEnv *, jobject, jstring, jobjectArray);

/*
 * Class:     com_couchbase_lite_storage_JavaSQLiteStorageEngine
 * Method:    _delete
 * Signature: (Ljava/lang/String;[Ljava/lang/Object;)I
 */
JNIEXPORT jint JNICALL Java_com_couchbase_lite_storage_JavaSQLiteStorageEngine__1delete
  (JNIEnv *, jobject, jstring, jobjectArray);

/*
 * Class:     com_couchbase_lite_storage_JavaSQLiteStorageEngine
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_couchbase_lite_storage_JavaSQLiteStorageEngine_close
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
