/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_couchbase_lite_storage_JavaSQLiteStorageEngine_StatementCursor */

#ifndef _Included_com_couchbase_lite_storage_JavaSQLiteStorageEngine_StatementCursor
#define _Included_com_couchbase_lite_storage_JavaSQLiteStorageEngine_StatementCursor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_couchbase_lite_storage_JavaSQLiteStorageEngine_StatementCursor
 * Method:    _next
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_couchbase_lite_storage_JavaSQLiteStorageEngine_00024StatementCursor__1next
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_couchbase_lite_storage_JavaSQLiteStorageEngine_StatementCursor
 * Method:    _getString
 * Signature: (JI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_couchbase_lite_storage_JavaSQLiteStorageEngine_00024StatementCursor__1getString
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_couchbase_lite_storage_JavaSQLiteStorageEngine_StatementCursor
 * Method:    _getInt
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_couchbase_lite_storage_JavaSQLiteStorageEngine_00024StatementCursor__1getInt
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_couchbase_lite_storage_JavaSQLiteStorageEngine_StatementCursor
 * Method:    _getLong
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_com_couchbase_lite_storage_JavaSQLiteStorageEngine_00024StatementCursor__1getLong
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_couchbase_lite_storage_JavaSQLiteStorageEngine_StatementCursor
 * Method:    _getBlob
 * Signature: (JI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_couchbase_lite_storage_JavaSQLiteStorageEngine_00024StatementCursor__1getBlob
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_couchbase_lite_storage_JavaSQLiteStorageEngine_StatementCursor
 * Method:    _close
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_couchbase_lite_storage_JavaSQLiteStorageEngine_00024StatementCursor__1close
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
