/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_couchbase_lite_database_sqlite_SQLiteQueryCursor */

#ifndef _Included_com_couchbase_lite_database_sqlite_SQLiteQueryCursor
#define _Included_com_couchbase_lite_database_sqlite_SQLiteQueryCursor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_couchbase_lite_database_sqlite_SQLiteQueryCursor
 * Method:    nativeMoveToNext
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_couchbase_lite_database_sqlite_SQLiteQueryCursor_nativeMoveToNext
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_couchbase_lite_database_sqlite_SQLiteQueryCursor
 * Method:    nativeIsAfterLast
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_couchbase_lite_database_sqlite_SQLiteQueryCursor_nativeIsAfterLast
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_couchbase_lite_database_sqlite_SQLiteQueryCursor
 * Method:    nativeGetString
 * Signature: (JI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_couchbase_lite_database_sqlite_SQLiteQueryCursor_nativeGetString
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_couchbase_lite_database_sqlite_SQLiteQueryCursor
 * Method:    nativeGetInt
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_couchbase_lite_database_sqlite_SQLiteQueryCursor_nativeGetInt
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_couchbase_lite_database_sqlite_SQLiteQueryCursor
 * Method:    nativeGetLong
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_com_couchbase_lite_database_sqlite_SQLiteQueryCursor_nativeGetLong
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_couchbase_lite_database_sqlite_SQLiteQueryCursor
 * Method:    nativeGetDouble
 * Signature: (JI)D
 */
JNIEXPORT jdouble JNICALL Java_com_couchbase_lite_database_sqlite_SQLiteQueryCursor_nativeGetDouble
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_couchbase_lite_database_sqlite_SQLiteQueryCursor
 * Method:    nativeGetBlob
 * Signature: (JI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_couchbase_lite_database_sqlite_SQLiteQueryCursor_nativeGetBlob
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_couchbase_lite_database_sqlite_SQLiteQueryCursor
 * Method:    nativeIsNull
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_com_couchbase_lite_database_sqlite_SQLiteQueryCursor_nativeIsNull
  (JNIEnv *, jclass, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
