/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_couchbase_lite_storage_SQLiteJsonCollator */

#ifndef _Included_com_couchbase_lite_storage_SQLiteJsonCollator
#define _Included_com_couchbase_lite_storage_SQLiteJsonCollator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_couchbase_lite_storage_SQLiteJsonCollator
 * Method:    nativeRegister
 * Signature: (JLjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_couchbase_lite_storage_SQLiteJsonCollator_nativeRegister
  (JNIEnv *, jclass, jlong, jstring, jstring);

/*
 * Class:     com_couchbase_lite_storage_SQLiteJsonCollator
 * Method:    nativeTestCollate
 * Signature: (IILjava/lang/String;ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_couchbase_lite_storage_SQLiteJsonCollator_nativeTestCollate
  (JNIEnv *, jclass, jint, jint, jstring, jint, jstring);

/*
 * Class:     com_couchbase_lite_storage_SQLiteJsonCollator
 * Method:    nativeTestCollateWithLocale
 * Signature: (ILjava/lang/String;ILjava/lang/String;ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_couchbase_lite_storage_SQLiteJsonCollator_nativeTestCollateWithLocale
  (JNIEnv *, jclass, jint, jstring, jint, jstring, jint, jstring);

/*
 * Class:     com_couchbase_lite_storage_SQLiteJsonCollator
 * Method:    nativeTestDigitToInt
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_couchbase_lite_storage_SQLiteJsonCollator_nativeTestDigitToInt
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_couchbase_lite_storage_SQLiteJsonCollator
 * Method:    nativeTestEscape
 * Signature: (Ljava/lang/String;)C
 */
JNIEXPORT jchar JNICALL Java_com_couchbase_lite_storage_SQLiteJsonCollator_nativeTestEscape
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
