/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_couchbase_lite_internal_database_security_Key */

#ifndef _Included_com_couchbase_lite_internal_database_security_Key
#define _Included_com_couchbase_lite_internal_database_security_Key
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_couchbase_lite_internal_database_security_Key
 * Method:    nativeDerivePBKDF2SHA256Key
 * Signature: (Ljava/lang/String;[BI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_couchbase_lite_internal_database_security_Key_nativeDerivePBKDF2SHA256Key
  (JNIEnv *, jclass, jstring, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
