/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_couchbase_lite_storage_SQLiteRevCollator */

#ifndef _Included_com_couchbase_lite_storage_SQLiteRevCollator
#define _Included_com_couchbase_lite_storage_SQLiteRevCollator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_couchbase_lite_storage_SQLiteRevCollator
 * Method:    nativeRegister
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_couchbase_lite_storage_SQLiteRevCollator_nativeRegister
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_couchbase_lite_storage_SQLiteRevCollator
 * Method:    nativeTestCollate
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_couchbase_lite_storage_SQLiteRevCollator_nativeTestCollate
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
