/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_couchbase_lite_database_sqlite_SQLiteConnection */

#ifndef _Included_com_couchbase_lite_database_sqlite_SQLiteConnection
#define _Included_com_couchbase_lite_database_sqlite_SQLiteConnection
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_couchbase_lite_database_sqlite_SQLiteConnection
 * Method:    nativeOpen
 * Signature: (Ljava/lang/String;ILjava/lang/String;ZZ)J
 */
JNIEXPORT jlong JNICALL Java_com_couchbase_lite_database_sqlite_SQLiteConnection_nativeOpen
  (JNIEnv *, jclass, jstring, jint, jstring, jboolean, jboolean);

/*
 * Class:     com_couchbase_lite_database_sqlite_SQLiteConnection
 * Method:    nativeClose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_couchbase_lite_database_sqlite_SQLiteConnection_nativeClose
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_couchbase_lite_database_sqlite_SQLiteConnection
 * Method:    nativePrepareStatement
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_couchbase_lite_database_sqlite_SQLiteConnection_nativePrepareStatement
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_couchbase_lite_database_sqlite_SQLiteConnection
 * Method:    nativeFinalizeStatement
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_couchbase_lite_database_sqlite_SQLiteConnection_nativeFinalizeStatement
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_couchbase_lite_database_sqlite_SQLiteConnection
 * Method:    nativeGetParameterCount
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_com_couchbase_lite_database_sqlite_SQLiteConnection_nativeGetParameterCount
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_couchbase_lite_database_sqlite_SQLiteConnection
 * Method:    nativeIsReadOnly
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_com_couchbase_lite_database_sqlite_SQLiteConnection_nativeIsReadOnly
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_couchbase_lite_database_sqlite_SQLiteConnection
 * Method:    nativeGetColumnCount
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_com_couchbase_lite_database_sqlite_SQLiteConnection_nativeGetColumnCount
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_couchbase_lite_database_sqlite_SQLiteConnection
 * Method:    nativeGetColumnName
 * Signature: (JJI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_couchbase_lite_database_sqlite_SQLiteConnection_nativeGetColumnName
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     com_couchbase_lite_database_sqlite_SQLiteConnection
 * Method:    nativeBindNull
 * Signature: (JJI)V
 */
JNIEXPORT void JNICALL Java_com_couchbase_lite_database_sqlite_SQLiteConnection_nativeBindNull
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     com_couchbase_lite_database_sqlite_SQLiteConnection
 * Method:    nativeBindLong
 * Signature: (JJIJ)V
 */
JNIEXPORT void JNICALL Java_com_couchbase_lite_database_sqlite_SQLiteConnection_nativeBindLong
  (JNIEnv *, jclass, jlong, jlong, jint, jlong);

/*
 * Class:     com_couchbase_lite_database_sqlite_SQLiteConnection
 * Method:    nativeBindDouble
 * Signature: (JJID)V
 */
JNIEXPORT void JNICALL Java_com_couchbase_lite_database_sqlite_SQLiteConnection_nativeBindDouble
  (JNIEnv *, jclass, jlong, jlong, jint, jdouble);

/*
 * Class:     com_couchbase_lite_database_sqlite_SQLiteConnection
 * Method:    nativeBindString
 * Signature: (JJILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_couchbase_lite_database_sqlite_SQLiteConnection_nativeBindString
  (JNIEnv *, jclass, jlong, jlong, jint, jstring);

/*
 * Class:     com_couchbase_lite_database_sqlite_SQLiteConnection
 * Method:    nativeBindBlob
 * Signature: (JJI[B)V
 */
JNIEXPORT void JNICALL Java_com_couchbase_lite_database_sqlite_SQLiteConnection_nativeBindBlob
  (JNIEnv *, jclass, jlong, jlong, jint, jbyteArray);

/*
 * Class:     com_couchbase_lite_database_sqlite_SQLiteConnection
 * Method:    nativeResetStatementAndClearBindings
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_couchbase_lite_database_sqlite_SQLiteConnection_nativeResetStatementAndClearBindings
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_couchbase_lite_database_sqlite_SQLiteConnection
 * Method:    nativeExecute
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_couchbase_lite_database_sqlite_SQLiteConnection_nativeExecute
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_couchbase_lite_database_sqlite_SQLiteConnection
 * Method:    nativeExecuteForLong
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_com_couchbase_lite_database_sqlite_SQLiteConnection_nativeExecuteForLong
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_couchbase_lite_database_sqlite_SQLiteConnection
 * Method:    nativeExecuteForString
 * Signature: (JJ)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_couchbase_lite_database_sqlite_SQLiteConnection_nativeExecuteForString
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_couchbase_lite_database_sqlite_SQLiteConnection
 * Method:    nativeExecuteForChangedRowCount
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_com_couchbase_lite_database_sqlite_SQLiteConnection_nativeExecuteForChangedRowCount
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_couchbase_lite_database_sqlite_SQLiteConnection
 * Method:    nativeExecuteForLastInsertedRowId
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_com_couchbase_lite_database_sqlite_SQLiteConnection_nativeExecuteForLastInsertedRowId
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_couchbase_lite_database_sqlite_SQLiteConnection
 * Method:    nativeGetDbLookaside
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_couchbase_lite_database_sqlite_SQLiteConnection_nativeGetDbLookaside
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_couchbase_lite_database_sqlite_SQLiteConnection
 * Method:    nativeCancel
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_couchbase_lite_database_sqlite_SQLiteConnection_nativeCancel
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_couchbase_lite_database_sqlite_SQLiteConnection
 * Method:    nativeResetCancel
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_com_couchbase_lite_database_sqlite_SQLiteConnection_nativeResetCancel
  (JNIEnv *, jclass, jlong, jboolean);

#ifdef __cplusplus
}
#endif
#endif
